Repository edp963/davinci, pull requests merged in 2020-11, with the labels that each got.

#2012 Fix: issue 2006 & 2007
  server/src/main/java/edp/davinci/common/utils/ScriptUtils.java
  server/src/main/java/edp/davinci/core/utils/ExcelUtils.java
  server/src/main/java/edp/davinci/core/utils/VizUtils.java
  server/src/main/java/edp/davinci/dto/viewDto/ViewExecuteParam.java
  server/src/main/java/edp/davinci/service/excel/WidgetContext.java
  server/src/main/java/edp/davinci/service/excel/WorkBookContext.java
  server/src/main/java/edp/davinci/service/excel/WorkbookWorker.java
  server/src/main/java/edp/davinci/service/impl/DownloadCommonService.java
  server/src/main/java/edp/davinci/service/impl/DownloadServiceImpl.java
  server/src/main/java/edp/davinci/service/impl/EmailScheduleServiceImpl.java
  server/src/main/java/edp/davinci/service/impl/ShareDownloadServiceImpl.java
  server/src/main/java/edp/davinci/service/impl/ShareServiceImpl.java
  server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java
  server/src/main/java/edp/davinci/service/impl/WidgetServiceImpl.java
  server/src/main/resources/templates/js/executeParam.js
Labels: bug

#2030 Fix: Global controller include or no include does not take effect
  config/application.yml.example
  server/src/main/java/edp/core/utils/SqlUtils.java
  server/src/main/java/edp/davinci/core/enums/SqlOperatorEnum.java
  server/src/main/java/edp/davinci/core/model/Criterion.java
  server/src/main/java/edp/davinci/core/model/SqlFilter.java
  server/src/main/java/edp/davinci/core/utils/SourcePasswordEncryptUtils.java
  server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java
Labels: bug

#2048 Enhancement: Chrome driver 'disable-dev-shm-usage' argument
  server/src/main/java/edp/davinci/service/screenshot/ScreenshotUtil.java
Labels: enhancement

#2036 fix: submit share download can not be Certified
  server/src/main/java/edp/davinci/controller/DownloadController.java
Labels: bug

#2049 Delete useless code
  server/src/main/java/edp/davinci/controller/OrganizationController.java
  server/src/main/java/edp/davinci/service/OrganizationService.java
  server/src/main/java/edp/davinci/service/impl/OrganizationServiceImpl.java
Labels: inactive

#2053 Delete useless code
  server/pom.xml
  server/src/main/java/edp/core/common/cache/Caches.java
  server/src/main/java/edp/core/config/CaffeineCacheConfig.java
  server/src/main/java/edp/core/utils/MailUtils.java
  server/src/main/java/edp/core/utils/SqlUtils.java
  server/src/main/java/edp/davinci/controller/DisplayController.java
  server/src/main/java/edp/davinci/controller/UserController.java
  server/src/main/java/edp/davinci/controller/ViewController.java
  server/src/main/java/edp/davinci/core/enums/SqlColumnEnum.java
  server/src/main/java/edp/davinci/core/utils/CsvUtils.java
  server/src/main/java/edp/davinci/core/utils/ExcelUtils.java
  server/src/main/java/edp/davinci/service/impl/CronJobServiceImpl.java
  server/src/main/java/edp/davinci/service/impl/DisplayServiceImpl.java
  server/src/main/java/edp/davinci/service/impl/SourceServiceImpl.java
  server/src/main/java/edp/davinci/service/impl/ViewServiceImpl.java
  server/src/main/resources/application.yml
Labels: inactive
